site_name: pydbtools
repo_url: https://github.com/moj-analytical-services/pydbtools

theme:
    name: tech_docs_template
    logo: logos/moj.png
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.indexes
    favicon: favicons/moj.ico

plugins:
    - mkdocstrings:
          custom_templates: templates
          default_handler: python
          handlers:
              python:
                  options:
                      show_source: false
    - material/search
    - mkdocs-jupyter

nav:
    - Home: "README.md"
    - User Guide:
          - Overview: guide/overview.md
    - Examples:
          - examples/create_temporary_tables_from_sql_file.ipynb
          - examples/create_temporary_tables.ipynb
          - examples/creating_and_maintaining_database_tables_in_athena_from_sql.ipynb
          - examples/creating_and_maintaining_database_tables_in_athena.ipynb
          - examples/delete_databases_tables_and_partitions.ipynb
          - examples/displaying_tables_example.ipynb
          - examples/mojap_tools_demo.ipynb
          - examples/simple_database_creation_manipulation.ipynb
          - examples/sql_templating.ipynb
          - examples/testing_new_awswrangler.ipynb
          - examples/updating_db_with_deltas.ipynb
    - API:
          - Wrangler Extensions: api/wrangler.md
          - SQL Rendering: api/sql_render.md
          - Utilities: api/utils.md
          - Depreciated: api/deprecated.md

markdown_extensions:
    - mdx_include
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true
    - admonition

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
