name: gh-deploy
on:
  push:
    branches:
      - main
    paths:
      - '**docs/**'
      - README.md
      - '**mkdocs.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false \
            && poetry install --no-interaction --no-ansi --only docs
      - run: mkdocs gh-deploy --force
